version: '3.8'

services:
  oracle:
    image: container-registry.oracle.com/database/free
    container_name: yeye-oracle
    environment:
      - ORACLE_SID=FREE
      - ORACLE_PDB=FREEPDB1
      - ORACLE_PWD=ora
      - INIT_SGA_SIZE=2000
      - INIT_PGA_SIZE=500
      - ORACLE_EDITION=developer
      - ENABLE_ARCHIVELOG=false
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - yeye-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
      - DB_URL=jdbc:oracle:thin:@oracle:1521/FREEPDB1
      - DB_USER=system
      - DB_PASSWORD=ora
      - LOG_LEVEL=INFO
    depends_on:
      oracle:
        condition: service_healthy
    networks:
      - yeye-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "User-Agent: Docker-Healthcheck/1.0", "http://localhost:8080/internal/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - yeye-network

volumes:
  oracle-data:
    name: yeye-oracle-data

networks:
  yeye-network:
    driver: bridge 