services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: yeye-oracle
    environment:
      - ORACLE_PWD=ora
    ports:
      - "1521:1521"
    networks:
      - yeye-network
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 45s
      timeout: 20s
      retries: 25
      start_period: 400s

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-Xmx512m -Dlogback.configurationFile=/app/logback.xml
      - DB_URL=jdbc:oracle:thin:@//oracle:1521/FREE
      - DB_USER=system
      - DB_PASSWORD=ora
      - LOG_LEVEL=DEBUG
      - DB_CONNECTION_RETRY_COUNT=30
      - DB_CONNECTION_RETRY_DELAY=10
    networks:
      - yeye-network
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/internal/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    networks:
      - yeye-network

volumes:
  oracle-data:
    name: yeye-oracle-data

networks:
  yeye-network:
    driver: bridge 