version: '3.8'

services:
  oracle:
    image: container-registry.oracle.com/database/free
    container_name: yeye-oracle
    environment:
      - ORACLE_SID=FREE
      - ORACLE_PDB=free
      - ORACLE_PWD=ora
      - INIT_SGA_SIZE=2000
      - INIT_PGA_SIZE=500
      - ORACLE_EDITION=developer
      - ENABLE_ARCHIVELOG=false
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - yeye-network
    healthcheck:
      test: ["CMD", "bash", "-c", "sqlplus -S system/ora@//localhost:1521/free <<< \"select 1 from dual;\" | grep -q \"1\""]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    command: |
      bash -c '
        echo "Starting Oracle database..." &&
        /opt/oracle/runOracle.sh &
        echo "Waiting for database to be ready..." &&
        while ! sqlplus -S / as sysdba <<< "select 1 from dual;" | grep -q "1"; do
          sleep 10;
          echo "Still waiting for database to be ready...";
        done &&
        echo "Database is ready!" &&
        echo "Starting Oracle Net Listener..." &&
        lsnrctl start &&
        echo "Listener started" &&
        echo "Configuring database..." &&
        sqlplus -S / as sysdba <<< "
          ALTER PLUGGABLE DATABASE free OPEN;
          ALTER PLUGGABLE DATABASE free SAVE STATE;
          ALTER USER system IDENTIFIED BY ora;
          GRANT CONNECT, RESOURCE, DBA TO system;
          EXEC DBMS_SERVICE.CREATE_SERVICE('free', 'free');
          EXEC DBMS_SERVICE.START_SERVICE('free');
          ALTER SYSTEM SET service_names='free' SCOPE=BOTH;
          ALTER SYSTEM REGISTER;
        " &&
        echo "Service configuration completed" &&
        echo "Checking listener status..." &&
        lsnrctl status &&
        echo "#########################" &&
        echo "DATABASE IS READY TO USE!" &&
        echo "#########################" &&
        tail -f /opt/oracle/diag/rdbms/*/*/trace/alert*.log
      '

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-Xmx512m
      - DB_URL=jdbc:oracle:thin:@//oracle:1521/free
      - DB_USER=system
      - DB_PASSWORD=ora
      - LOG_LEVEL=INFO
    depends_on:
      oracle:
        condition: service_healthy
    networks:
      - yeye-network
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "User-Agent: Docker-Healthcheck/1.0", "http://localhost:8081/internal/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - yeye-network

volumes:
  oracle-data:
    name: yeye-oracle-data
    external: true

networks:
  yeye-network:
    driver: bridge 