services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: yeye-oracle
    environment:
      - ORACLE_PWD=ora
      - ORACLE_SID=FREE
    ports:
      - "1521:1521"
    networks:
      - yeye-network
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/ora@//localhost:1521/FREE", "SELECT 1 FROM DUAL"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:oracle:thin:@//oracle:1521/FREE
      - DB_USER=system
      - DB_PASSWORD=ora
      - DB_CONNECTION_RETRY_COUNT=30
      - DB_CONNECTION_RETRY_DELAY=10
    networks:
      - yeye-network
    restart: on-failure:5
    depends_on:
      oracle:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    networks:
      - yeye-network
    depends_on:
      backend:
        condition: service_healthy

volumes:
  oracle-data:
    name: yeye-oracle-data

networks:
  yeye-network:
    driver: bridge